import {test,after} from 'node:test';import assert from 'node:assert/strict';import {Pool} from 'pg';import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import {randomUUID} from 'node:crypto';import Stripe from 'stripe';
const schema='kepler_test_'+Date.now();const root=new Pool({connectionString:process.env.TEST_DATABASE_URL||'postgresql://localhost/kepler_local'});await root.query('CREATE SCHEMA '+schema);const testUrl=new URL(process.env.TEST_DATABASE_URL||'postgresql://localhost/kepler_local');testUrl.searchParams.set('options','-c search_path='+schema+',public');process.env.DATABASE_URL=testUrl.toString();
const {pool,query}=await import('../lib/db');const {prepareOrder}=await import('../lib/commerce');const {digest,token}=await import('../lib/security');const {reconcileSession,processEvent,reconcilePending,StripeProvider}=await import('../lib/payments');const {runNotifications}=await import('../lib/jobs');await pool.query(await readFile('migrations/001_kepler.sql','utf8'));
after(async()=>{await pool.end();await root.query('DROP SCHEMA '+schema+' CASCADE');await root.end();});
const address={name:'Isolated Test',email:'nobody@example.invalid',phone:'+971500000000',emirate:'Dubai' as const,area:'Test',street:'Test',unit:''};
await query("UPDATE settings SET value=$1 WHERE key='commerce'",[JSON.stringify({sellingEnabled:true,pricesApproved:true,inventoryApproved:true,policiesApproved:true,fulfillmentApproved:true,shippingApproved:true,taxApproved:true,taxBps:0,taxInclusive:false,shippingZones:[{id:'test',name:'test',emirates:['Dubai'],feeMinor:0,description:'test'}]})]);
async function fixture(stock=1){const p=(await query("INSERT INTO products(slug,sku,name,category,mode,price_minor,stock,review_status) VALUES($1,'ISOLATED','Test fixture','bms','buy',10000,$2,'approved') RETURNING id",['test-'+randomUUID(),stock]))[0];const c=(await query('INSERT INTO carts(token_hash,items) VALUES($1,$2) RETURNING id',[digest(token()),JSON.stringify([{productId:p.id,quantity:1}])]))[0];return {productId:p.id as string,cartId:c.id as string};}
async function order(f:Awaited<ReturnType<typeof fixture>>){return (await prepareOrder(f.cartId,address,randomUUID(),token())).order;}
function session(o:{id:string;total_minor:number},status='complete',payment='paid'){return {id:'cs_test_'+o.id,metadata:{orderId:o.id},client_reference_id:o.id,status,payment_status:payment,currency:'aed',amount_total:o.total_minor,payment_intent:'pi_test_'+o.id} as unknown as Stripe.Checkout.Session;}
function event(type:string,s:Stripe.Checkout.Session,id='evt_'+randomUUID()){return {id,type,data:{object:s}} as unknown as Stripe.Event;}
test('concurrent buyers cannot reserve the final unit',async()=>{const f=await fixture();const c=(await query('INSERT INTO carts(token_hash,items) VALUES($1,$2) RETURNING id',[digest(token()),JSON.stringify([{productId:f.productId,quantity:1}])]))[0];const results=await Promise.allSettled([order(f),order({...f,cartId:c.id as string})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected').length,1);});
test('payment success visit is not proof; repeated and duplicate webhooks consume stock once',async()=>{const f=await fixture(2);const o=await order(f);await reconcileSession(session(o,'open','unpaid'));assert.equal((await query('SELECT status FROM orders WHERE id=$1',[o.id]))[0].status,'pending');const e=event('checkout.session.completed',session(o));await Promise.all([processEvent(e),processEvent(e)]);await processEvent(event('checkout.session.completed',session(o)));assert.equal((await query('SELECT stock FROM products WHERE id=$1',[f.productId]))[0].stock,1);assert.equal((await query('SELECT status FROM orders WHERE id=$1',[o.id]))[0].status,'paid');assert.equal((await query('SELECT count(*)::int n FROM notification_jobs WHERE event_key=$1',['order-paid:'+o.id]))[0].n,1);assert.equal((await query('SELECT count(*)::int n FROM analytics_events'))[0].n,0);await assert.rejects(query('UPDATE orders SET total_minor=1 WHERE id=$1',[o.id]));});
test('cancelled and failed payments release reservations; delayed verified payment reacquires safely',async()=>{const f=await fixture();const o=await order(f);await reconcileSession(session(o,'expired','unpaid'));assert.equal((await query('SELECT status FROM orders WHERE id=$1',[o.id]))[0].status,'cancelled');await processEvent(event('checkout.session.async_payment_succeeded',session(o)));assert.equal((await query('SELECT status FROM orders WHERE id=$1',[o.id]))[0].status,'paid');assert.equal((await query('SELECT stock FROM products WHERE id=$1',[f.productId]))[0].stock,0);const failed=await order(await fixture());await processEvent(event('checkout.session.async_payment_failed',session(failed,'complete','unpaid')));assert.equal((await query('SELECT status FROM orders WHERE id=$1',[failed.id]))[0].status,'failed');});
test('delayed payment with stock already consumed requires review and never fulfills',async()=>{const f=await fixture();const late=await order(f);await reconcileSession(session(late,'expired','unpaid'));const newer=await order(f);await reconcileSession(session(newer));await reconcileSession(session(late));assert.equal((await query('SELECT status FROM orders WHERE id=$1',[late.id]))[0].status,'payment_review');assert.equal((await query('SELECT stock FROM products WHERE id=$1',[f.productId]))[0].stock,0);});
test('amount tampering and invalid webhook signatures are rejected',async()=>{const o=await order(await fixture());await assert.rejects(reconcileSession({...session(o),amount_total:1}));process.env.STRIPE_SECRET_KEY='sk_test_isolated_invalid';process.env.STRIPE_WEBHOOK_SECRET='whsec_isolated';assert.throws(()=>new StripeProvider().verify('{}','invalid'));delete process.env.STRIPE_SECRET_KEY;delete process.env.STRIPE_WEBHOOK_SECRET;});
test('expired or revised quotation and cross-customer quote conversion are denied',async()=>{const f=await fixture(3);const staff=(await query("INSERT INTO staff(email,role) VALUES('test@example.invalid','admin') RETURNING id"))[0];const e=(await query("INSERT INTO enquiries(reference,access_hash,cart_id,name,contact_method,contact,project_type,location,requirements) VALUES($1,$2,$3,'Test','email','test@example.invalid','Test','Test','Isolated test') RETURNING id",[randomUUID(),digest(token()),f.cartId]))[0];const q=(await query("INSERT INTO quotations(enquiry_id,version,token_hash,lines,valid_until,terms,approved_by) VALUES($1,1,$2,$3,now()+interval '1 hour','Test terms',$4) RETURNING id",[e.id,digest(token()),JSON.stringify([{productId:f.productId,quantity:1,unitMinor:7000}]),staff.id]))[0];const result=await prepareOrder(f.cartId,address,randomUUID(),token(),q.id as string);assert.equal(result.order.subtotal_minor,7000);const other=await fixture();await assert.rejects(prepareOrder(other.cartId,address,randomUUID(),token(),q.id as string));await query('UPDATE quotations SET revoked=true WHERE id=$1',[q.id]);await assert.rejects(prepareOrder(f.cartId,address,randomUUID(),token(),q.id as string));await query("UPDATE quotations SET revoked=false,valid_until=now()-interval '1 hour' WHERE id=$1",[q.id]);await assert.rejects(prepareOrder(f.cartId,address,randomUUID(),token(),q.id as string));});
test('refund-before-payment retry and older partial refund do not regress full refund',async()=>{const o=await order(await fixture());const full={id:'evt_refund_'+randomUUID(),type:'charge.refunded',data:{object:{payment_intent:'pi_test_'+o.id,amount_refunded:o.total_minor,currency:'aed'}}} as unknown as Stripe.Event;await assert.rejects(processEvent(full));await reconcileSession(session(o));await processEvent(full);await processEvent({...full,id:'evt_partial_'+randomUUID(),data:{object:{...(full.data.object as Stripe.Charge),amount_refunded:100}}} as Stripe.Event);assert.equal((await query('SELECT status FROM orders WHERE id=$1',[o.id]))[0].status,'refunded');assert.equal((await query('SELECT status FROM payments WHERE order_id=$1',[o.id]))[0].status,'refunded');});
test('unknown expired creation is released only after provider confirms no session',async()=>{const o=await order(await fixture());await query("UPDATE orders SET expires_at=now()-interval '10 minutes' WHERE id=$1",[o.id]);const mock={recover:async()=>null,retrieve:async()=>{throw new Error('fixture')},expire:async()=>{throw new Error('fixture')},create:async()=>{throw new Error('fixture')},verify:()=>{throw new Error('fixture')}};await reconcilePending(mock);assert.equal((await query('SELECT status FROM orders WHERE id=$1',[o.id]))[0].status,'cancelled');});
test('notification retries use a stable dedupe key and no actual email is sent',async()=>{await query("DELETE FROM notification_jobs");const o=await order(await fixture());await reconcileSession(session(o));let calls=0;const mock={send:async()=>{calls++;return 'fixture-accepted';}};await runNotifications(mock);await runNotifications(mock);assert.equal(calls,1);assert.equal((await query("SELECT count(*)::int n FROM notification_jobs WHERE status='sent'"))[0].n,1);});
test('repeat source imports do not duplicate records or overwrite approved staff edits',async()=>{
 const dir=await mkdtemp(path.join(tmpdir(),'kepler-import-'));const source='https://example.invalid/2026/10/05/ked-isolated/';
 const fixture={url:source,canonical:source,id:'isolated',title:'KED-ISOLATED',html:'',text:'Original isolated import',categories:['products','smart-locks'],tags:[],assets:[],specs:{},sku:'KED-ISOLATED',brand:null,status:200,fetchedAt:new Date().toISOString(),hash:'fixture-first',screenshot:null,visualStatus:'test-fixture',reviewFlags:[]};
 const file=path.join(dir,'source.json');await writeFile(file,JSON.stringify([fixture]));
 const run=()=>new Promise<void>((resolve,reject)=>{const child=spawn(process.execPath,['--import','tsx','scripts/migration/import.ts'],{env:{...process.env,DATABASE_URL:testUrl.toString(),MIGRATION_SOURCE_FILE:file,MIGRATION_OUTPUT_DIR:path.join(dir,'output'),MIGRATION_REPORT_FILE:path.join(dir,'report.md')},stdio:['ignore','ignore','pipe']});let error='';child.stderr.on('data',b=>error+=b);child.on('error',reject);child.on('exit',code=>code===0?resolve():reject(new Error(error||'Import failed')));});
 try{await run();await run();assert.equal((await query('SELECT count(*)::int n FROM products WHERE source_url=$1',[source]))[0].n,1);await query("UPDATE products SET name='Reviewed staff name',description='Approved staff description',edited_at=now(),review_status='approved' WHERE source_url=$1",[source]);fixture.text='Changed source text';fixture.hash='fixture-second';await writeFile(file,JSON.stringify([fixture]));await run();const row=(await query('SELECT name,description,source_hash FROM products WHERE source_url=$1',[source]))[0];assert.equal(row.name,'Reviewed staff name');assert.equal(row.description,'Approved staff description');assert.equal(row.source_hash,'fixture-first');}finally{await rm(dir,{recursive:true,force:true});}
});
