import {test} from 'node:test';import assert from 'node:assert/strict';import {classify,category} from '../scripts/migration/import';import {calculate,addressSchema,ensureSelling,purchaseLine,type CommerceSettings} from '../lib/commerce';import {validateFile,safeCsv} from '../lib/uploads';import {passwordHash,checkPassword} from '../lib/security';import {publicProduct} from '../lib/catalog';import type {Product} from '../lib/types';
const address=addressSchema.parse({name:'Test Buyer',email:'buyer@example.invalid',phone:'+971500000000',emirate:'Dubai',area:'Test area',street:'Test building',unit:''});
const settings:CommerceSettings={sellingEnabled:true,pricesApproved:true,inventoryApproved:true,policiesApproved:true,fulfillmentApproved:true,shippingApproved:true,taxApproved:true,taxBps:500,taxInclusive:false,shippingTaxable:true,shippingZones:[{id:'test',name:'Dubai test',emirates:['Dubai'],feeMinor:1000,description:'Isolated fixture'}]};
const product={id:'00000000-0000-4000-8000-000000000001',name:'Fixture',sku:'TEST',published:true,mode:'buy',review_status:'approved',price_minor:10000,stock:1,source_url:'https://example.invalid'} as Product;
test('archives, real projects, locks and sample merchandise are classified separately',()=>{assert.equal(classify({url:'https://kepler-elec.com/category/company/projects-and-references/',title:'Products',categories:['projects-and-references'],sku:null}),'archive');assert.equal(classify({url:'https://kepler-elec.com/2024/04/20/mama/',title:'MAMA',categories:['projects-and-references'],sku:null}),'project');assert.equal(category({url:'https://kepler-elec.com/ked-m098/',title:'KED-M098',categories:['door-locks'],tags:[]}),'smart-locks');assert.equal(category({url:'https://kepler-elec.com/lroc/',title:'LROC-40x Room Controller',categories:['dali'],tags:[]}),'grms');assert.equal(classify({url:'https://kepler-elec.com/product/woo-ninja/',title:'Woo Ninja',categories:[],sku:null}),'excluded-demo');});
test('AED integer totals and inclusive/exclusive tax are calculated without a US address',()=>{const line=purchaseLine(product,{productId:product.id,quantity:2});assert.equal(calculate([line],settings,address).total,22050);const inclusive=calculate([line],{...settings,taxInclusive:true},address);assert.equal(inclusive.total,21000);assert.equal(inclusive.tax,1000);assert.throws(()=>calculate([line],settings,{...address,emirate:'Ajman'}));assert.throws(()=>ensureSelling({...settings,taxApproved:false}));});
test('quote-only and unresolved products cannot be purchased or expose unapproved prices',()=>{assert.throws(()=>purchaseLine({...product,mode:'quote'},{productId:product.id,quantity:1}));assert.throws(()=>purchaseLine(product,{productId:product.id,quantity:1.1}));assert.throws(()=>purchaseLine(product,{productId:product.id,quantity:1,variantId:'unpriced'}));assert.equal(publicProduct({...product,mode:'quote',review_status:'source-review-pending'}).price_minor,null);});
test('documents require valid content signatures; CSV exports neutralize formula cells',()=>{assert.throws(()=>validateFile({name:'unsafe.svg',size:5},Buffer.from('hello')));assert.throws(()=>validateFile({name:'fake.pdf',size:5},Buffer.from('hello')));assert.equal(validateFile({name:'test.csv',size:7},Buffer.from('a,b\n1,2')),'text/csv');assert.match(safeCsv('=IMPORTXML("evil")'),/^"'/);});
test('staff passwords are salted and checked without default credentials',()=>{const hash=passwordHash('isolated-password-for-test');assert.ok(checkPassword('isolated-password-for-test',hash));assert.ok(!checkPassword('wrong',hash));assert.ok(!checkPassword('wrong','bad'));assert.notEqual(passwordHash('same-password'),passwordHash('same-password'));});
