import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import {pool} from '../../lib/db';import {categories as taxonomy} from '../../lib/types';
type Source={url:string;canonical:string;id:string;title:string;html:string;text:string;categories:string[];tags:string[];assets:{source:string;alt:string;kind:string;path?:string;status?:number}[];specs:Record<string,string>;sku:string|null;brand:string|null;status:number;fetchedAt:string;hash:string;screenshot:string|null;visualStatus:string;reviewFlags:string[]};
export function classify(s:Pick<Source,'url'|'title'|'categories'|'sku'>){
 if(/\/product\/(ship-your-idea|woo-|patient-ninja|happy-ninja|ninja-silhouette|flying-ninja|premium-quality)/.test(s.url)||/^(Hello world!|Sample Page)$/.test(s.title))return 'excluded-demo';
 if(/company-profile/.test(s.url))return 'company';
 if(/\/(category|tag|brand|product-category|product-tag|product-brand)\//.test(s.url)||/\/(products|shop|posts|sonoff)(\/page\/\d+)?\/?$/.test(s.url))return 'archive';
 if(s.url.includes('/product/')&&/nike|hurley|tennis|golf|sleeveless|tank|skirt|jacket|sports bra|training|indy|rib racer|nylon core|flex bliss|tempo|dri-fit|sportswear/i.test(s.title))return 'excluded-demo';
 if(s.categories.includes('projects-and-references'))return 'project';
 if(/privacy-policy/.test(s.url))return 'legacy-policy';
 if(/contact-us|request-quote/.test(s.url)||new URL(s.url).pathname==='/')return 'company';
 if(/\/dali-2\/?$/.test(s.url))return 'resource';
 if(/^[A-Z][A-Z0-9-]+(?:\s|$)/.test(s.title)&&/[0-9-]/.test(s.title.split(' ')[0]))return 'product';
 if(/l-dali/.test(s.url))return 'product';
 if(s.categories.includes('products')||s.url.includes('/product/')||s.sku||s.categories.some(c=>/^(bms-software|grms-software|l-web|accessories|interfaces|lpad7|l-vis|l-roc|l-inx|l-iob|l-stat|ldali|lgate|l-ip|i-o-controllers|i-o-modules|room-controllers|automation-servers|touch-screen|touch-screens|touch-pad|thermostat|dimmers|gateway|relay-module|lighting-sensors|dali-controller|dmx-controller|dali-drivers)/.test(c)))return 'product';
 if(s.categories.includes('uncategorized')&&!s.url.includes('/product/'))return 'resource';
 if(s.categories.some(c=>/newsroom|corporate-news|product-news/.test(c)))return 'news';
 return 'review';
}
export function category(s:Pick<Source,'categories'|'tags'|'url'|'title'>){const text=[...s.categories,...s.tags,s.title,s.url].join(' ').toLowerCase();
 if(/door-lock|smart.?lock/.test(text))return 'smart-locks';if(/touch.?screens|touch.?panels|lpad|l-vis|lvis|hmi|l-stat/.test(text))return 'touchscreens';if(/sonoff/.test(text))return 'sonoff';if(/lroc|l-roc/.test(s.title.toLowerCase()))return 'grms';if(/lighting-control|dali|dmx|dimmer/.test(text))return 'lighting-control';if(/\bbms\b|l-inx|linx|l-iob|liob/.test(text))return 'bms';if(/\bgrms\b|lroc|l-roc/.test(text))return 'grms';if(/gateway|connectivity|l-ip|lgate/.test(text))return 'connectivity';if(/standalone/.test(text))return 'standalone';if(/accessories|power-supply|control-cables/.test(text))return 'accessories';return 'home-automation';}
async function main(){
 const assetIndex:Record<string,unknown>[] = JSON.parse(await readFile('data/source/assets.json','utf8').catch(()=>'[]'));const derived=new Map(assetIndex.map(a=>[a.source,a]));
 const snaps:Source[]=JSON.parse(await readFile(process.env.MIGRATION_SOURCE_FILE||'data/source/snapshots.json','utf8'));const manifest=[];const queue=[];const redirects:{source:string;destination:string;permanent:boolean}[]=[];let products=0,projects=0,content=0;
 for(const s of snaps){const kind=s.status===200?classify(s):'inaccessible';const rawSlug=new URL(s.url).pathname.split('/').filter(Boolean).at(-1)||'home';let slug=rawSlug;const allImages=s.assets.filter(a=>a.path&&a.kind==='image');const model=(s.sku||s.title.split(' ')[0]).toLowerCase().replace(/[^a-z0-9]/g,'').replace(/x$/, '');const own=allImages.filter(a=>new URL(a.source).pathname.split('/').at(-1)!.toLowerCase().replace(/[^a-z0-9]/g,'').includes(model));const selected=kind==='product'&&own.length?own:allImages;const media=selected.map(a=>{const d=derived.get(a.source);return {path:(d?.displayPath as string)||a.path!,alt:a.alt||s.title,source:a.source,...(d?.width?{width:d.width,height:d.height}:{})};});const downloads=s.assets.filter(a=>a.path&&a.kind==='download').map(a=>({path:a.path!,alt:a.alt,source:a.source}));let destination:string|null=null;
  const target=kind==='product'?'products':kind==='project'?'projects':['resource','company','news','legacy-policy'].includes(kind)?'content':null;for(const table of ['products','projects','content'])if(table!==target)await pool.query(`DELETE FROM ${table} WHERE source_url=$1 AND edited_at IS NULL`,[s.url]);
  if(kind==='product'){
   const collision=(await pool.query('SELECT source_url FROM products WHERE slug=$1',[slug])).rows[0];if(collision&&collision.source_url!==s.url)slug+='-'+createHash('sha256').update(s.url).digest('hex').slice(0,5);
   const protocols=['BACnet','DALI','Modbus','KNX','EnOcean','Zigbee','Bluetooth','Wi-Fi','LON','MQTT'].filter(p=>new RegExp(p.replace('-','[- ]'),'i').test([s.text,...s.tags].join(' ')));
   const cat=category(s);const sku=s.sku&&s.sku!=='N/A'?s.sku: (s.title.includes('|')&&/^[A-Za-z0-9-]+$/.test(s.title.split('|').at(-1)!.trim())?s.title.split('|').at(-1)!.trim():/^SONOFF\b/i.test(s.title)?null:/^[A-Z][A-Z0-9-]+(?:\s|$)/.exec(s.title)?.[0].trim()||null);const brand=s.brand||([...s.tags,...s.categories,s.text].join(' ').match(/\bLOYTEC\b/i)?'LOYTEC':/sonoff/i.test(s.url)?'SONOFF':null);
   const variants=/\/loytec-lpad-7\/?$/.test(s.url)?['LPAD7-30G2','LPAD7-30G3','LPAD7-31G2','LPAD7-31G3','LPAD7-41G2','LPAD7-41G3'].filter(model=>s.text.includes(model)).map(model=>({id:model.toLowerCase(),name:model,sku:model,specs:{'Source confirmation':'Listed in the original LPAD-7 product family. Confirm exact revision and optional socket before ordering.'}})):[];
   await pool.query(`INSERT INTO products(slug,sku,name,description,category,categories,brand,protocols,applications,specs,media,downloads,source_url,source_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(source_url) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,category=EXCLUDED.category,sku=EXCLUDED.sku,brand=EXCLUDED.brand,protocols=EXCLUDED.protocols,categories=EXCLUDED.categories,specs=EXCLUDED.specs,media=EXCLUDED.media,downloads=EXCLUDED.downloads,source_hash=EXCLUDED.source_hash WHERE products.edited_at IS NULL`,[slug,sku,s.title,s.text,cat,s.categories,brand,protocols,s.categories.filter(c=>/residential|hospitality|commercial|villas|apartments|buildings/.test(c)),JSON.stringify(s.specs),JSON.stringify(media),JSON.stringify(downloads),s.url,s.hash]);await pool.query('UPDATE products SET variants=$2 WHERE source_url=$1 AND edited_at IS NULL',[s.url,JSON.stringify(variants)]);products++;destination='/products/'+slug;
  }else if(kind==='project'){
   const collision=(await pool.query('SELECT source_url FROM projects WHERE slug=$1',[slug])).rows[0];if(collision&&collision.source_url!==s.url)slug+='-'+createHash('sha256').update(s.url).digest('hex').slice(0,5);
   await pool.query(`INSERT INTO projects(slug,name,description,media,source_url,source_hash) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(source_url) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,media=EXCLUDED.media,source_hash=EXCLUDED.source_hash WHERE projects.edited_at IS NULL`,[slug,s.title,s.text,JSON.stringify(media),s.url,s.hash]);await pool.query('UPDATE projects SET scope=$2,location=$3 WHERE source_url=$1 AND edited_at IS NULL',[s.url,/(?:Systems?|Solutions?)\s*:\s*(.+?)(?=\s*(?:Location|Companies|Company)\s*:|$)/i.exec(s.text)?.[1]?.trim()||null,/Location\s*:\s*(.+?)(?=\s*(?:Systems?|Solutions?|Companies|Company)\s*:|$)/i.exec(s.text)?.[1]?.trim()||null]);projects++;destination='/projects/'+slug;
  }else if(['resource','company','news','legacy-policy'].includes(kind)){
   const collision=(await pool.query('SELECT source_url FROM content WHERE slug=$1',[slug])).rows[0];if(collision&&collision.source_url!==s.url)slug+='-'+createHash('sha256').update(s.url).digest('hex').slice(0,5);
   await pool.query(`INSERT INTO content(slug,title,kind,body,media,downloads,source_url,source_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(source_url) DO UPDATE SET title=EXCLUDED.title,body=EXCLUDED.body,media=EXCLUDED.media,downloads=EXCLUDED.downloads,source_hash=EXCLUDED.source_hash WHERE content.edited_at IS NULL`,[slug,s.title,kind,s.text,JSON.stringify(media),JSON.stringify(downloads),s.url,s.hash]);content++;destination=kind==='legacy-policy'?'/policies/legacy-app-privacy':kind==='company'?(slug==='contact-us'?'/contact':slug==='request-quote'?'/quote':slug==='home'?'/':'/about'):'/resources/'+slug;
  }else if(kind==='archive'){
   destination=/projects-and-references/.test(s.url)?'/projects':/company/.test(s.url)?'/about':/loytec/.test(s.url)?'/loytec':/newsroom/.test(s.url)?'/resources':/sonoff/.test(s.url)?'/products/category/sonoff':'/products';
   for(const [key] of Object.entries(taxonomy))if(s.url.includes(key)||key==='home-automation'&&s.url.includes('iot-home-automation'))destination='/products/category/'+key;
  }
  if(destination){const source=new URL(s.url).pathname.replace(/\/$/,'')||'/';if(source!==destination&&source!=='/'){redirects.push({source,destination,permanent:true},{source:'/index.php'+source,destination,permanent:true});await pool.query('INSERT INTO redirects(source,destination) VALUES($1,$2) ON CONFLICT(source) DO UPDATE SET destination=EXCLUDED.destination WHERE redirects.review_status!=\'approved\'',[source,destination]);}}
  if(['review','inaccessible','excluded-demo'].includes(kind)||s.reviewFlags.length)queue.push({source:s.url,classification:kind,flags:s.reviewFlags,reason:kind==='excluded-demo'?'WooCommerce sample merchandise excluded from technical catalog':kind==='review'?'Unclassified content requires editorial review':null});
  manifest.push({sourceUrl:s.url,canonicalUrl:s.canonical,sourceId:s.id,fetchedTime:s.fetchedAt,originalTitle:s.title,classification:kind,destination,assets:s.assets,contentHash:s.hash,importStatus:destination?'imported':kind==='excluded-demo'?'excluded':'review-required',reviewFlags:s.reviewFlags,visualInspectionStatus:s.visualStatus,screenshot:s.screenshot});
 }
 await pool.query("DELETE FROM projects WHERE edited_at IS NULL AND (source_url LIKE '%/category/%' OR source_url LIKE '%/tag/%')");
 const output=process.env.MIGRATION_OUTPUT_DIR||'data/migration';await mkdir(output,{recursive:true});await writeFile(output+'/manifest.json',JSON.stringify(manifest,null,2));await writeFile(output+'/redirects.json',JSON.stringify(redirects,null,2));await writeFile(output+'/review-queue.json',JSON.stringify(queue,null,2));
 const summary={snapshots:snaps.length,reachable:snaps.filter(x=>x.status===200).length,products,projects,content,redirects:redirects.length,captured:snaps.filter(x=>x.screenshot).length,contactSheetsReviewed:snaps.filter(x=>x.visualStatus.includes('contact-sheet-reviewed')).length,fullDetailReviewed:snaps.filter(x=>x.visualStatus.includes('full-detail-reviewed')).length,excluded:manifest.filter(x=>x.classification==='excluded-demo').length};
 await pool.query('INSERT INTO import_runs(summary) VALUES($1)',[JSON.stringify(summary)]);
 await writeFile(process.env.MIGRATION_REPORT_FILE||'docs/MIGRATION_REPORT.md',`# Source migration\n\nUpdated: ${new Date().toISOString()}\n\n${Object.entries(summary).map(([k,v])=>`- ${k}: ${v}`).join('\n')}\n\nThese are actual captured/imported counts, not a claim of whole-site completeness. Source snapshots are kept in data/source/snapshots.json. The manifest, redirect map and review queue are in data/migration.\n\nThe public WordPress REST endpoint returned 401 (authentication required). Command-line requests returned 403; the public browser surface returned 200. The resumable crawler uses the normal browser, sitemaps, navigation and pagination at a bounded rate. No login or access restriction was bypassed.\n\nCatalog imports are quote-only, with null prices and null inventory. Source prices are not approval to sell. Company claims, certification statements, technical descriptions and asset rights remain flagged for review. Project references have no invented scope. WooCommerce sample merchandise is excluded.\n\nReruns update only untouched imported records; admin edits set edited_at and are preserved. Review queue records include pending source/rights review and inaccessible pages. A captured screenshot is not a completed visual inspection.\n`);
 console.log(summary);await pool.end();
}
if(process.argv[1]?.endsWith('import.ts'))await main();
