import { readFile } from 'node:fs/promises';
import { repoPath } from './renderer.mjs';
const source=JSON.parse(await readFile(`${repoPath}/data/site-snapshot.json`));
const featured=['loytec-lpad-7','ked-m098','kzig','lroc-40'].map(key=>source.products.find(p=>p.slug.includes(key)||p.sku?.toLowerCase()===key)).filter(Boolean);
const chosen=[...new Map([...featured,...source.products.slice(0,12)].map(p=>[p.slug,p])).values()];
export const toProduct=(p,index)=>{
  const media=p.media.map((m,i)=>({...m,url:m.path,id:index*100+i+1,media_type:'image',preview_image:{...m,url:m.path}}));
  const variants=(p.variants.length?p.variants:[{sku:p.sku,name:'Default Title'}]).map((v,i)=>({id:String(100000+index*100+i),title:v.name||v.sku,sku:v.sku||p.sku,available:false,price:0,compare_at_price:null,quantity_rule:{min:1,increment:1,max:null},featured_media:media[0]}));
  return {id:index+1,handle:p.slug,title:p.name,vendor:p.brand,url:`/products/${p.slug}`,description:`<p>${p.description.slice(0,650).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</p>`,featured_image:media[0],featured_media:media[0],media,variants,has_only_default_variant:variants.length===1,selected_or_first_available_variant:variants[0],options_with_values:variants.length>1?[{name:'Model',values:variants.map((v,i)=>({id:String(i+1),selected:i===0,name:v.title}))}]:[],price:0,price_varies:false,metafields:{kepler:{commercial_mode:{value:'quote'},specifications:{value:p.specs},source_url:{value:p.source_url},documents:{value:p.downloads.map(d=>({label:d.alt,url:`https://github.com/BaderAsad1/kepler-electronics/releases/download/source-assets-v1/${d.path.split('/').pop()}`}))}}},selling_plan_groups:[]};
};
export const products=chosen.map(toProduct);
const demo={...products[0],id:999,handle:'fixture-buy-product',title:'Shopify purchase test fixture',url:'/products/fixture-buy-product',metafields:{kepler:{commercial_mode:{value:'buy'}}},variants:products[0].variants.map((v,i)=>({...v,id:String(900001+i),price:149900+i*10000,compare_at_price:i===0?169900:null,available:i!==2,sku:`TEST-${i+1}`})),price:149900};
demo.selected_or_first_available_variant=demo.variants[0];demo.options_with_values=[{name:'Model',values:demo.variants.map((v,i)=>({id:String(i+1),selected:i===0,name:v.title}))}];
export const buyProduct=demo;
export function variantProduct(product,query){
 const selected=product.variants.find(v=>v.id===query.get('variant'))||product.variants[Number(query.get('option_values')||1)-1]||product.variants[0];
 return {...product,selected_or_first_available_variant:selected,options_with_values:product.options_with_values.map(o=>({...o,values:o.values.map((v,i)=>({...v,selected:product.variants[i].id===selected.id}))}))};
}
const nav=[['Solutions','/pages/solutions'],['Products','/collections/all'],['Projects','/pages/projects'],['About','/pages/about'],['Resources','/pages/resources']].map(([title,url])=>({title,url,links:[]}));
export function scope(url,cart={items:[],item_count:0,total_price:0,note:''}){
 return {settings:{enable_commerce:true,color_background:'#F4F1EB',color_ink:'#111315',color_accent:'#164B49',content_width:1320,heading_style:'sans',phone:'+971 4 324 4835',email:'sales@kepler-elec.com',address:source.settings.contact.address,contact_page:{url:'/pages/contact'},quote_page:{url:'/pages/project-quote'}},request:{page_type:'index',design_mode:false,locale:{iso_code:url.searchParams.get('lang')||'en'}},shop:{name:'Kepler Electronics',url:url.origin,customer_accounts_enabled:true,policies:[],enabled_payment_types:[],shipping_policy:{body:''}},routes:{root_url:'/',all_products_collection_url:'/collections/all',cart_url:'/cart',cart_change_url:'/cart/change',search_url:'/search',account_url:'/account'},cart:{...cart,currency:{iso_code:'AED'},taxes_included:false,cart_level_discount_applications:[]},page_title:'Kepler Electronics',canonical_url:url.origin+url.pathname,current_page:1,localization:{country:{iso_code:'AE'},available_countries:[{iso_code:'AE',name:'United Arab Emirates',currency:{iso_code:'AED'}}],available_languages:[{iso_code:'en',endonym_name:'English'}]},fixtureMenus:{'main-menu':{links:nav},footer:{links:[{title:'Contact',url:'/pages/contact'}]}},collections:{all:{url:'/collections/all',title:'Explore the technology.',description:'<p>Exact models. Original documents. A considered technology pathway.</p>',products,products_count:products.length,sort_options:[{value:'manual',name:'Featured'},{value:'title-ascending',name:'Alphabetically, A–Z'}],default_sort_by:'manual',filters:[{label:'Brand',type:'list',values:[{label:'LOYTEC',value:'LOYTEC',param_name:'filter.p.vendor',count:products.length,active:false}]}]}},products};
}
