import {PoolClient} from 'pg';import {z} from 'zod';import {Product,Line} from './types';import {query,transaction} from './db';import {HttpError,digest} from './security';
export const emirates=['Dubai','Abu Dhabi','Sharjah','Ajman','Umm Al Quwain','Ras Al Khaimah','Fujairah'];
export const addressSchema=z.object({name:z.string().trim().min(2).max(120),email:z.email().max(180),phone:z.string().regex(/^[+\d ()-]{7,25}$/),emirate:z.enum(['Dubai','Abu Dhabi','Sharjah','Ajman','Umm Al Quwain','Ras Al Khaimah','Fujairah']),area:z.string().trim().min(2).max(120),street:z.string().trim().min(2).max(250),unit:z.string().max(100),instructions:z.string().max(1000).optional(),company:z.string().max(180).optional(),taxNumber:z.string().max(60).optional()}).strict();
export type Address=z.infer<typeof addressSchema>;
export type CommerceSettings={sellingEnabled:boolean;pricesApproved:boolean;inventoryApproved:boolean;policiesApproved:boolean;fulfillmentApproved:boolean;shippingApproved:boolean;taxApproved:boolean;taxBps:number|null;taxInclusive:boolean;shippingTaxable?:boolean;shippingZones:{id:string;name:string;emirates:string[];feeMinor:number;freeAboveMinor?:number|null;description:string}[]};
export type SnapshotLine={productId:string;sku:string|null;name:string;quantity:number;unitMinor:number;lineMinor:number;currency:string;sourceUrl:string;variantId?:string|null};
export type Order={id:string;reference:string;access_hash:string;cart_id:string;status:string;currency:string;subtotal_minor:number;tax_minor:number;shipping_minor:number;total_minor:number;address:Address;lines:SnapshotLine[];provider_session:string|null;checkout_key:string;expires_at:string;paid_at:string|null;created_at:string};
export function ensureSelling(s:CommerceSettings){if(!s||!s.sellingEnabled||!s.pricesApproved||!s.inventoryApproved||!s.policiesApproved||!s.fulfillmentApproved||!s.shippingApproved||!s.taxApproved||s.taxBps===null)throw new HttpError(503,'Online purchasing is not enabled. Please request a project quotation.');if(!Number.isInteger(s.taxBps)||s.taxBps<0||s.taxBps>10000)throw new HttpError(503,'Approved tax configuration is required.');}
export function calculate(lines:SnapshotLine[],s:CommerceSettings,address:Address){const zone=s.shippingZones.find(z=>z.emirates.includes(address.emirate));if(!zone)throw new HttpError(400,'Delivery is not configured for this emirate. Please discuss fulfillment with our team.');if(!Number.isInteger(zone.feeMinor)||zone.feeMinor<0)throw new HttpError(503,'An approved delivery rate is required.');const subtotal=lines.reduce((n,l)=>n+l.lineMinor,0);const shipping=zone.freeAboveMinor&&subtotal>=zone.freeAboveMinor?0:zone.feeMinor;const taxable=subtotal+(s.shippingTaxable?shipping:0);const tax=s.taxInclusive?taxable-Math.round(taxable*10000/(10000+s.taxBps!)):Math.round(taxable*s.taxBps!/10000);const total=subtotal+shipping+(s.taxInclusive?0:tax);if(!Number.isSafeInteger(total)||total<=0||total>100000000)throw new HttpError(400,'This order requires a managed quotation.');return {subtotal,tax,shipping,total,zone};}
export function purchaseLine(p:Product,l:Line):SnapshotLine{if(!p.published||p.mode!=='buy'||p.review_status!=='approved'||!p.price_minor||p.stock===null)throw new HttpError(400,`${p.name} is not approved for purchase. Request a quotation.`);if(!Number.isInteger(l.quantity)||l.quantity<1||l.quantity>999)throw new HttpError(400,'Invalid product quantity.');if(l.variantId)throw new HttpError(400,'Variant purchasing requires a separately approved SKU. Please request a quotation.');return {productId:p.id,sku:p.sku,name:p.name,quantity:l.quantity,unitMinor:p.price_minor,lineMinor:p.price_minor*l.quantity,currency:'AED',sourceUrl:p.source_url};}
async function settings(db:PoolClient){return (await db.query('SELECT value FROM settings WHERE key=\'commerce\'')).rows[0]?.value as CommerceSettings;}
export async function prepareOrder(cartId:string,address:Address,checkoutKey:string,accessToken:string,quotationId?:string,analyticsConsent=false){return transaction(async db=>{const c=(await db.query('SELECT * FROM carts WHERE id=$1 FOR UPDATE',[cartId])).rows[0];if(!c)throw new HttpError(401,'Your shopping session could not be found.');const s=await settings(db);ensureSelling(s);const key=digest(cartId+':'+checkoutKey);const existing=(await db.query('SELECT * FROM orders WHERE checkout_key=$1',[key])).rows[0] as Order|undefined;if(existing){if(existing.access_hash!==digest(accessToken))throw new HttpError(409,'Restart checkout with a new session.');return {order:existing,settings:s};}
 let cartLines=c.items as Line[];let quoteLines:{productId:string;quantity:number;unitMinor:number}[]|null=null;
 if(quotationId){const quote=(await db.query('SELECT * FROM quotations WHERE id=$1 FOR UPDATE',[quotationId])).rows[0];const enquiry=quote?(await db.query('SELECT cart_id FROM enquiries WHERE id=$1',[quote.enquiry_id])).rows[0]:null;if(!quote||quote.revoked||new Date(quote.valid_until).getTime()<=Date.now()||enquiry?.cart_id!==cartId)throw new HttpError(403,'This quotation is expired, revised, or not authorized for your session.');quoteLines=quote.lines;cartLines=quoteLines!.map(l=>({productId:l.productId,quantity:l.quantity}));}
 if(!cartLines.length)throw new HttpError(400,'Your shopping bag is empty.');if(new Set(cartLines.map(l=>l.productId)).size!==cartLines.length)throw new HttpError(400,'Duplicate product lines are not accepted.');const products=(await db.query('SELECT * FROM products WHERE id=ANY($1::uuid[]) ORDER BY id FOR UPDATE',[cartLines.map(l=>l.productId)])).rows as Product[];if(products.length!==cartLines.length)throw new HttpError(400,'A selected product is no longer available.');const lines=cartLines.map(l=>{const p=products.find(p=>p.id===l.productId)!;const line=purchaseLine(p,l);if(quoteLines){const approved=quoteLines.find(q=>q.productId===p.id)!;if(!Number.isInteger(approved.unitMinor)||approved.unitMinor<=0)throw new HttpError(400,'Quoted pricing is not approved.');line.unitMinor=approved.unitMinor;line.lineMinor=approved.unitMinor*l.quantity;}return line;});
 for(const l of lines){const held=Number((await db.query('SELECT COALESCE(sum(quantity),0) AS quantity FROM reservations WHERE product_id=$1 AND state=\'reserved\'',[l.productId])).rows[0].quantity);const p=products.find(p=>p.id===l.productId)!;if(p.stock!-held<l.quantity)throw new HttpError(409,`${p.name} has insufficient available stock. Update the quantity or request a quotation.`);}
 const total=calculate(lines,s,address);const ref='KO-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+checkoutKey.slice(0,8).toUpperCase();const order=(await db.query('INSERT INTO orders(reference,access_hash,cart_id,quotation_id,subtotal_minor,tax_minor,shipping_minor,total_minor,address,lines,checkout_key,analytics_consent,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,now()+interval \'35 minutes\') RETURNING *',[ref,digest(accessToken),cartId,quotationId||null,total.subtotal,total.tax,total.shipping,total.total,JSON.stringify(address),JSON.stringify(lines),key,analyticsConsent])).rows[0] as Order;
 for(const l of lines)await db.query('INSERT INTO reservations(order_id,product_id,quantity,expires_at) VALUES($1,$2,$3,$4)',[order.id,l.productId,l.quantity,order.expires_at]);return {order,settings:s};});}
export async function getOrder(id:string){return (await query<Order>('SELECT * FROM orders WHERE id=$1',[id]))[0];}
