import Stripe from 'stripe';import {Order,CommerceSettings} from './commerce';import {query,transaction} from './db';import {HttpError} from './security';
export interface PaymentProvider{create(order:Order,settings:CommerceSettings,access:string):Promise<{id:string;url:string}>;retrieve(id:string):Promise<Stripe.Checkout.Session>;expire(id:string):Promise<Stripe.Checkout.Session>;verify(body:string,signature:string):Stripe.Event;recover?(order:Order):Promise<Stripe.Checkout.Session|null>;}
export class StripeProvider implements PaymentProvider{private client:Stripe;constructor(){const key=process.env.STRIPE_SECRET_KEY;if(!key)throw new HttpError(503,'Hosted payments are not configured. Please request a quotation.');if(process.env.SITE_ENV!=='production'&&!key.startsWith('sk_test_'))throw new HttpError(503,'Only test payment credentials are allowed in this environment.');this.client=new Stripe(key);}
 async create(order:Order,settings:CommerceSettings,access:string){const base=process.env.NEXT_PUBLIC_SITE_URL||'http://localhost:3000';const lines:Stripe.Checkout.SessionCreateParams.LineItem[]=order.lines.map(l=>({quantity:l.quantity,price_data:{currency:'aed',unit_amount:l.unitMinor,product_data:{name:l.name,metadata:{sku:l.sku||'',productId:l.productId}}}}));if(order.shipping_minor)lines.push({quantity:1,price_data:{currency:'aed',unit_amount:order.shipping_minor,product_data:{name:'Approved UAE delivery'}}});if(!settings.taxInclusive&&order.tax_minor)lines.push({quantity:1,price_data:{currency:'aed',unit_amount:order.tax_minor,product_data:{name:'Approved tax'}}});const session=await this.client.checkout.sessions.create({mode:'payment',line_items:lines,customer_email:order.address.email,client_reference_id:order.id,metadata:{orderId:order.id},success_url:base+'/order?id='+order.id+'&access='+encodeURIComponent(access),cancel_url:base+'/checkout?cancelled=1',expires_at:Math.floor(new Date(order.expires_at).getTime()/1000),payment_intent_data:{metadata:{orderId:order.id}}},{idempotencyKey:order.checkout_key});if(!session.url)throw new Error('Hosted checkout did not return a URL.');return {id:session.id,url:session.url};}
 async recover(order:Order){let after:string|undefined;for(let page=0;page<100;page++){const result=await this.client.checkout.sessions.list({limit:100,created:{gte:Math.floor(new Date(order.created_at).getTime()/1000)-60},...(after?{starting_after:after}:{})});const match=result.data.find(s=>s.metadata?.orderId===order.id);if(match)return match;if(!result.has_more)return null;after=result.data.at(-1)?.id;}throw new Error('Session recovery requires staff review: bounded lookup exhausted.');}
 retrieve(id:string){return this.client.checkout.sessions.retrieve(id);}
 expire(id:string){return this.client.checkout.sessions.expire(id);}
 verify(body:string,signature:string){if(!process.env.STRIPE_WEBHOOK_SECRET)throw new HttpError(503,'Webhook verification is not configured.');return this.client.webhooks.constructEvent(body,signature,process.env.STRIPE_WEBHOOK_SECRET);}
}
export function provider(){return new StripeProvider();}
export async function startCheckout(order:Order,settings:CommerceSettings,access:string,p:PaymentProvider=provider()){if(order.status!=='pending')throw new HttpError(409,'This order is no longer awaiting payment.');if(order.provider_session){const existing=await p.retrieve(order.provider_session);if(existing.status==='open'&&existing.url)return {url:existing.url,orderId:order.id};await reconcileSession(existing);throw new HttpError(409,'This payment session has ended. Review your order status.');}try{const session=await p.create(order,settings,access);await query('UPDATE orders SET provider_session=$2 WHERE id=$1 AND provider_session IS NULL',[order.id,session.id]);return {url:session.url,orderId:order.id};}catch(e){/* An uncertain provider response must keep reservations until retry/reconciliation. */await query('INSERT INTO notification_jobs(event_key,kind,payload) VALUES($1,\'checkout_review\',$2) ON CONFLICT DO NOTHING',['checkout-review:'+order.id,JSON.stringify({orderId:order.id})]);throw e;}}
export async function reconcileSession(session:Stripe.Checkout.Session){return transaction(async db=>{const id=session.metadata?.orderId||session.client_reference_id;if(!id)return;const order=(await db.query('SELECT * FROM orders WHERE id=$1 FOR UPDATE',[id])).rows[0] as Order|undefined;if(!order)return;if(order.provider_session&&order.provider_session!==session.id)throw new Error('Checkout session mismatch.');if(session.payment_status==='paid'){
  if(session.currency?.toUpperCase()!=='AED'||session.amount_total!==order.total_minor)throw new Error('Verified payment amount/currency mismatch.');const intent=typeof session.payment_intent==='string'?session.payment_intent:session.payment_intent?.id;if(!intent)throw new Error('Paid session has no payment identifier.');await db.query('INSERT INTO payments(order_id,provider_payment,amount_minor,currency,status) VALUES($1,$2,$3,\'AED\',\'paid\') ON CONFLICT(provider_payment) DO NOTHING',[order.id,intent,order.total_minor]);if(['paid','fulfilled','refunded','payment_review'].includes(order.status))return;
  const reservations=(await db.query('SELECT * FROM reservations WHERE order_id=$1 ORDER BY product_id FOR UPDATE',[order.id])).rows;let canConsume=true;for(const r of reservations){const product=(await db.query('SELECT stock FROM products WHERE id=$1 FOR UPDATE',[r.product_id])).rows[0];const held=Number((await db.query('SELECT COALESCE(sum(quantity),0) AS quantity FROM reservations WHERE product_id=$1 AND state=\'reserved\' AND order_id!=$2',[r.product_id,order.id])).rows[0].quantity);if(product?.stock===null||product?.stock-held<r.quantity)canConsume=false;}
  if(!canConsume||reservations.length!==order.lines.length){await db.query('UPDATE orders SET status=\'payment_review\',paid_at=COALESCE(paid_at,now()),provider_session=$2 WHERE id=$1',[order.id,session.id]);await db.query('INSERT INTO notification_jobs(event_key,kind,payload) VALUES($1,\'payment_review\',$2) ON CONFLICT DO NOTHING',['payment-review:'+order.id,JSON.stringify({orderId:order.id})]);return;}
  for(const r of reservations){if(r.state!=='consumed'){await db.query('UPDATE products SET stock=stock-$2,updated_at=now() WHERE id=$1',[r.product_id,r.quantity]);await db.query('UPDATE reservations SET state=\'consumed\' WHERE id=$1',[r.id]);}}
  await db.query('UPDATE orders SET status=\'paid\',paid_at=COALESCE(paid_at,now()),provider_session=$2 WHERE id=$1',[order.id,session.id]);await db.query('INSERT INTO notification_jobs(event_key,kind,payload) VALUES($1,\'order_paid\',$2) ON CONFLICT DO NOTHING',['order-paid:'+order.id,JSON.stringify({orderId:order.id})]);if((order as Order&{analytics_consent:boolean}).analytics_consent)await db.query('INSERT INTO analytics_events(dedupe_key,name,data) VALUES($1,\'purchase\',$2) ON CONFLICT DO NOTHING',['purchase:'+order.id,JSON.stringify({orderId:order.id,valueMinor:order.total_minor,currency:'AED'})]);
 }else if(session.status==='expired'&&['pending','failed'].includes(order.status)){await db.query('UPDATE orders SET status=\'cancelled\',provider_session=COALESCE(provider_session,$2) WHERE id=$1',[order.id,session.id]);await db.query('UPDATE reservations SET state=\'released\' WHERE order_id=$1 AND state=\'reserved\'',[order.id]);}else if(session.payment_status==='unpaid'&&session.status==='complete'){/* Await asynchronous payment outcome; no fulfillment. */}
 });}
export async function processEvent(event:Stripe.Event){await query('INSERT INTO webhook_events(id,type,payload) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[event.id,event.type,JSON.stringify(event)]);return transaction(async db=>{const row=(await db.query('SELECT * FROM webhook_events WHERE id=$1 FOR UPDATE',[event.id])).rows[0];if(row.status==='processed')return;await db.query('UPDATE webhook_events SET attempts=attempts+1 WHERE id=$1',[event.id]);/* The event remains durable if the independent reconciliation fails. */return row;}).then(async(row)=>{if(!row)return;
  try{if(event.type.startsWith('checkout.session.')){const session=event.data.object as Stripe.Checkout.Session;await reconcileSession(session);if(event.type==='checkout.session.async_payment_failed')await transaction(async db=>{const id=session.metadata?.orderId;const order=(await db.query('SELECT status FROM orders WHERE id=$1 FOR UPDATE',[id])).rows[0];if(order?.status==='pending'){await db.query('UPDATE orders SET status=\'failed\' WHERE id=$1',[id]);await db.query('UPDATE reservations SET state=\'released\' WHERE order_id=$1 AND state=\'reserved\'',[id]);}});}else if(event.type==='charge.refunded'){const charge=event.data.object as Stripe.Charge;const intent=typeof charge.payment_intent==='string'?charge.payment_intent:charge.payment_intent?.id;if(intent)await transaction(async db=>{const payment=(await db.query('SELECT * FROM payments WHERE provider_payment=$1 FOR UPDATE',[intent])).rows[0];if(!payment)throw new Error('Refund arrived before its payment. Retry after reconciliation.');if(charge.currency.toUpperCase()!==payment.currency||charge.amount_refunded>payment.amount_minor)throw new Error('Refund amount mismatch.');await db.query('UPDATE payments SET refund_minor=GREATEST(refund_minor,$2),status=CASE WHEN GREATEST(refund_minor,$2)=amount_minor THEN \'refunded\' ELSE \'partially_refunded\' END,updated_at=now() WHERE id=$1',[payment.id,charge.amount_refunded]);if(charge.amount_refunded===payment.amount_minor)await db.query('UPDATE orders SET status=\'refunded\' WHERE id=$1',[payment.order_id]);});}
  await query('UPDATE webhook_events SET status=\'processed\',processed_at=now(),error=NULL WHERE id=$1',[event.id]);
 }catch(e){await query('UPDATE webhook_events SET status=\'pending\',error=$2 WHERE id=$1',[event.id,(e as Error).message]);throw e;}
 });}
export async function reconcilePending(p:PaymentProvider=provider()){const orders=await query<Order>('SELECT * FROM orders WHERE status IN(\'pending\',\'failed\',\'cancelled\') AND created_at>now()-interval \'7 days\'');for(const order of orders){try{if(order.provider_session){let session=await p.retrieve(order.provider_session);if(session.status==='open'&&new Date(order.expires_at).getTime()<Date.now())session=await p.expire(session.id);await reconcileSession(session);}else{const session=await p.recover?.(order);if(session){await query('UPDATE orders SET provider_session=$2 WHERE id=$1 AND provider_session IS NULL',[order.id,session.id]);let current=session;if(current.status==='open'&&new Date(order.expires_at).getTime()<Date.now())current=await p.expire(current.id);await reconcileSession(current);}else if(p.recover&&new Date(order.expires_at).getTime()+5*60*1000<Date.now()){await transaction(async db=>{const row=(await db.query("SELECT status,provider_session FROM orders WHERE id=$1 FOR UPDATE",[order.id])).rows[0];if(row?.status==='pending'&&!row.provider_session){await db.query("UPDATE orders SET status='cancelled' WHERE id=$1",[order.id]);await db.query("UPDATE reservations SET state='released' WHERE order_id=$1 AND state='reserved'",[order.id]);}});}else{await query('INSERT INTO notification_jobs(event_key,kind,payload) VALUES($1,\'checkout_review\',$2) ON CONFLICT DO NOTHING',['checkout-review:'+order.id,JSON.stringify({orderId:order.id})]);}}}catch(e){console.error('Payment reconciliation deferred:',order.reference,(e as Error).message);}}const events=await query<{payload:Stripe.Event}>('SELECT payload FROM webhook_events WHERE status=\'pending\' ORDER BY created_at LIMIT 100');for(const e of events)await processEvent(e.payload).catch(()=>{});}
