import {createHash,randomBytes,scryptSync,timingSafeEqual} from 'node:crypto';import {cookies} from 'next/headers';import {NextRequest,NextResponse} from 'next/server';import {query} from './db';
export const token=()=>randomBytes(32).toString('base64url');export const digest=(s:string)=>createHash('sha256').update(s).digest('hex');
export class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
export function origin(req:NextRequest){const value=req.headers.get('origin');if(!value||![new URL(req.url).origin,process.env.NEXT_PUBLIC_SITE_URL].includes(value))throw new HttpError(403,'This request must come from this website.');}
export async function rateLimit(req:NextRequest,scope:string,max=15,minutes=15){const ip=req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'local';const key=digest(scope+':'+ip);const rows=await query<{hits:number}>(`INSERT INTO rate_limits(key,hits,expires_at) VALUES($1,1,now()+($2||' minutes')::interval) ON CONFLICT(key) DO UPDATE SET hits=CASE WHEN rate_limits.expires_at<now() THEN 1 ELSE rate_limits.hits+1 END,expires_at=CASE WHEN rate_limits.expires_at<now() THEN EXCLUDED.expires_at ELSE rate_limits.expires_at END RETURNING hits`,[key,minutes]);if(rows[0].hits>max)throw new HttpError(429,'Too many attempts. Please try again later.');}
export type Staff={id:string;email:string;role:'admin'|'editor'|'sales'|'fulfillment'};
export async function staff(){const value=(await cookies()).get('kepler_staff')?.value;if(!value)return null;return (await query<Staff>('SELECT s.id,s.email,s.role FROM sessions x JOIN staff s ON s.id=x.staff_id WHERE x.token_hash=$1 AND x.expires_at>now() AND s.disabled=false',[digest(value)]))[0]||null;}
export async function requireStaff(roles:Staff['role'][]=['admin']){const user=await staff();if(!user)throw new HttpError(401,'Staff sign-in is required.');if(!roles.includes(user.role))throw new HttpError(403,'Your role cannot perform this action.');return user;}
export const passwordHash=(password:string)=>{const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(password,salt,64).toString('hex');};
export const checkPassword=(password:string,hash:string)=>{try{const [salt,key]=hash.split(':');const actual=scryptSync(password,salt,64);const expected=Buffer.from(key,'hex');return actual.length===expected.length&&timingSafeEqual(actual,expected);}catch{return false;}};
export function cookieOptions(){return {httpOnly:true,secure:process.env.SITE_ENV==='production',sameSite:'lax' as const,path:'/',maxAge:60*60*24*30};}
export function failure(e:unknown){if(e instanceof HttpError)return NextResponse.json({error:e.message},{status:e.status});if(e&&typeof e==='object'&&'issues' in e)return NextResponse.json({error:'Please check the form fields and try again.'},{status:400});console.error('Kepler request failed:',e instanceof Error?e.message:'Unknown error');return NextResponse.json({error:'We couldn’t complete this request. Please try again.'},{status:500});}
