import {mkdir,writeFile,readFile} from 'node:fs/promises';import path from 'node:path';import {createHash,createHmac,timingSafeEqual} from 'node:crypto';import {createClient} from '@supabase/supabase-js';import {HttpError,token} from './security';
export const MAX_UPLOAD=10*1024*1024;
const root=()=>path.resolve(process.env.PRIVATE_STORAGE_PATH||'data/private');
export function validateFile(file:{name:string;size:number},buffer:Buffer){if(file.size>MAX_UPLOAD||file.size===0)throw new HttpError(400,'Upload a non-empty PDF, XLSX or CSV of up to 10 MB.');const ext=path.extname(file.name).toLowerCase();if(!['.pdf','.xlsx','.csv'].includes(ext))throw new HttpError(400,'Only PDF, XLSX and CSV files are accepted.');if(ext==='.pdf'&&buffer.subarray(0,5).toString()!=='%PDF-')throw new HttpError(400,'The document is not a valid PDF file.');if(ext==='.xlsx'&&!buffer.subarray(0,4).equals(Buffer.from([80,75,3,4])))throw new HttpError(400,'The document is not an XLSX archive.');if(ext==='.csv'&&(buffer.includes(0)||buffer.toString('utf8').includes('\ufffd')))throw new HttpError(400,'CSV uploads must be UTF-8 text.');return ext==='.pdf'?'application/pdf':ext==='.xlsx'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'text/csv';}
function cloud(){if(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY)return createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});return null;}
export async function storePrivate(file:File){const buffer=Buffer.from(await file.arrayBuffer());const mime=validateFile(file,buffer);const key='quarantine/'+token();const client=cloud();if(client){const {error}=await client.storage.from('private-boqs').upload(key,buffer,{contentType:mime,upsert:false});if(error)throw new Error('Private storage write failed.');}else{await mkdir(path.join(root(),'quarantine'),{recursive:true,mode:0o700});await writeFile(path.join(root(),key),buffer,{mode:0o600});}return {key,mime,sha256:createHash('sha256').update(buffer).digest('hex'),size:buffer.length,name:path.basename(file.name).replace(/[\r\n]/g,'').slice(0,180)};}
export async function readPrivate(key:string){if(!/^quarantine\/[A-Za-z0-9_-]{43}$/.test(key))throw new HttpError(400,'Invalid private file reference.');const client=cloud();if(client){const {data,error}=await client.storage.from('private-boqs').download(key);if(error||!data)throw new HttpError(404,'Document not found.');return Buffer.from(await data.arrayBuffer());}return readFile(path.join(root(),key));}
async function signingKey(){if(process.env.UPLOAD_SIGNING_SECRET)return process.env.UPLOAD_SIGNING_SECRET;await mkdir(root(),{recursive:true,mode:0o700});const file=path.join(root(),'.signing-key');try{return await readFile(file,'utf8');}catch{const key=token();await writeFile(file,key,{mode:0o600,flag:'wx'}).catch(()=>{});return readFile(file,'utf8');}}
export async function signFile(id:string,expires:number){return createHmac('sha256',await signingKey()).update(id+':'+expires).digest('hex');}
export async function checkFileSignature(id:string,expires:number,signature:string){if(expires<Date.now()||expires>Date.now()+6*60*1000)return false;const expected=Buffer.from(await signFile(id,expires),'hex');const actual=Buffer.from(signature,'hex');return expected.length===actual.length&&timingSafeEqual(expected,actual);}
export function safeCsv(value:unknown){const str=String(value??'');return '"'+(/^[=+\-@\t\r]/.test(str)?"'"+str:str).replaceAll('"','""')+'"';}
