import {cp,mkdir,readFile,writeFile,readdir,rm,symlink,link} from 'node:fs/promises';import path from 'node:path';import {spawn} from 'node:child_process';
const cwd=process.cwd();const build=path.join(cwd,'.pages-app');const base=process.env.PAGES_BASE_PATH||'/kepler-electronics';const site=process.env.PAGES_SITE_URL||'https://baderasad1.github.io/kepler-electronics';
// Only this generated build directory is replaced. Source app and backend stay intact.
await rm(build,{recursive:true,force:true});await mkdir(build,{recursive:true});for(const item of ['app','components','lib','data/site-snapshot.json','tsconfig.json','postcss.config.mjs','package.json','package-lock.json']){await mkdir(path.dirname(path.join(build,item)),{recursive:true});await cp(path.join(cwd,item),path.join(build,item),{recursive:true});}
await rm(path.join(build,'app/api'),{recursive:true,force:true});await symlink(path.join(cwd,'node_modules'),path.join(build,'node_modules'),'dir');await mkdir(path.join(build,'public'));await cp(path.join(cwd,'public/catalog-data.json'),path.join(build,'public/catalog-data.json'));
const snapshot=JSON.parse(await readFile(path.join(build,'data/site-snapshot.json'),'utf8'));for(const collection of [snapshot.products,snapshot.projects,snapshot.content])for(const entity of collection)for(const m of [...(entity.media||[]),...(entity.downloads||[])])if(m.path.startsWith('/'))m.path=base+m.path;await writeFile(path.join(build,'data/site-snapshot.json'),JSON.stringify(snapshot));
async function walk(dir:string){const results:string[]=[];for(const d of await readdir(dir,{withFileTypes:true})){const p=path.join(dir,d.name);if(d.isDirectory())results.push(...await walk(p));else results.push(p);}return results;}
for(const file of [...await walk(path.join(build,'app')),...await walk(path.join(build,'components'))]){if(!/\.(tsx?|css)$/.test(file))continue;let s=await readFile(file,'utf8');s=s.replaceAll('/images/editorial/',base+'/images/editorial/').replaceAll('/media/c9616f9fd5bd90d5.png',base+'/media/c9616f9fd5bd90d5.png').replaceAll('action="/products"','action="'+base+'/products"');await writeFile(file,s);}
await writeFile(path.join(build,'next.config.ts'),`import type {NextConfig} from 'next';const config:NextConfig={output:'export',trailingSlash:true,basePath:${JSON.stringify(base)},images:{unoptimized:true},poweredByHeader:false,agentRules:false};export default config;`);
const result=await new Promise<number>(resolve=>{const child=spawn(process.execPath,[path.join(cwd,'node_modules/next/dist/bin/next'),'build','--webpack'],{cwd:build,stdio:'inherit',env:{...process.env,NEXT_PUBLIC_STATIC_MODE:'true',NEXT_PUBLIC_BASE_PATH:base,NEXT_PUBLIC_SITE_URL:site,SITE_ENV:'preview'}});child.on('exit',c=>resolve(c||0));});if(result!==0)process.exit(result);
const publishedPaths=new Set(['/media/c9616f9fd5bd90d5.png',...snapshot.products.flatMap((p:{media:{path:string}[];downloads:{path:string}[]})=>[...p.media,...p.downloads].map(m=>m.path.slice(base.length))),...snapshot.projects.flatMap((p:{media:{path:string}[]})=>p.media.map(m=>m.path.slice(base.length))),...snapshot.content.flatMap((p:{media:{path:string}[];downloads:{path:string}[]})=>[...p.media,...p.downloads].map(m=>m.path.slice(base.length)))]);
const out=path.join(build,'out');for(const file of await walk(path.join(cwd,'public'))){if(file.endsWith('catalog-data.json'))continue;const publicPath='/'+path.relative(path.join(cwd,'public'),file);if(publicPath.startsWith('/media/')&&!publishedPaths.has(publicPath))continue;const dest=path.join(out,path.relative(path.join(cwd,'public'),file));await mkdir(path.dirname(dest),{recursive:true});await link(file,dest);}const catalog=JSON.parse(await readFile(path.join(out,'catalog-data.json'),'utf8'));for(const p of catalog)for(const m of p.media||[])m.path=base+m.path;await writeFile(path.join(out,'catalog-data.json'),JSON.stringify(catalog));
const redirects=JSON.parse(await readFile('data/migration/redirects.json','utf8'));for(const r of redirects){if(r.source.includes(':')||r.source==='/'||r.source.startsWith('/products/category/'))continue;const target=base+r.destination+'/';const dir=path.join(out,r.source);await mkdir(dir,{recursive:true});const encoded=JSON.stringify(target).replaceAll('<','\\u003c');await writeFile(path.join(dir,'index.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="robots" content="noindex"><link rel="canonical" href="${site.replace(/\/$/,'')+r.destination}"><meta http-equiv="refresh" content="0;url=${target}"><title>Page moved — Kepler Electronics</title></head><body><p>This page has moved. <a href="${target}">Continue to the corresponding page</a>.</p><script>location.replace(${encoded}+location.search+location.hash)</script></body></html>`);}
const documents=JSON.parse(await readFile('data/migration/download-redirects.json','utf8'));for(const alias of documents){const dest=path.join(out,alias.source);await mkdir(path.dirname(dest),{recursive:true});await link(path.join(cwd,'public',alias.destination),dest);}
await writeFile(path.join(out,'.nojekyll'),'');await writeFile('data/pages-build.json',JSON.stringify({builtAt:new Date().toISOString(),output:out,basePath:base,url:site,mode:'public catalog and local project list; backend not connected'},null,2));console.log('GitHub Pages output ready:',out);
